export const LOAD_NAV_ART_CARDS = 'LOAD_NAV_ART_CARDS';
export const LOAD_NAV_ART_CARDS_START = 'LOAD_NAV_ART_CARDS_START';
export const LOAD_NAV_ART_CARDS_SUCCESS = 'LOAD_NAV_ART_CARDS_SUCCESS';
export const LOAD_NAV_ART_CARDS_FAIL = 'LOAD_NAV_ART_CARDS_FAIL';