export const LOAD_ART_CARDS_START = 'LOAD_ART_CARDS_START';
export const LOAD_ART_CARDS_SUCCESS = 'LOAD_ART_CARDS_SUCCESS';
export const LOAD_ART_CARDS_FAIL = 'LOAD_ART_CARDS_FAIL';
export const LOAD_ARTICLE_START = 'LOAD_ARTICLE_START';
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS';
export const LOAD_ARTICLE_FAIL = 'LOAD_ARTICLE_FAIL';