export const SET_PRICELIST_CONTENT = 'SET_PRICELIST_CONTENT';
export const SET_PRICELIST_CONTENT_START = 'SET_PRICELIST_CONTENT_START';
export const SET_PRICELIST_CONTENT_SUCCESS = 'SET_PRICELIST_CONTENT_SUCCESS';
export const SET_PRICELIST_CONTENT_FAIL = 'SET_PRICELIST_CONTENT_FAIL';