export const SET_APP_CONTENT = 'SET_APP_CONTENT';
export const SET_APP_CONTENT_START = 'SET_APP_CONTENT_START';
export const SET_APP_CONTENT_SUCCESS = 'SET_APP_CONTENT_SUCCESS';
export const SET_APP_CONTENT_FAIL = 'SET_APP_CONTENT_FAIL';